new changes
Danchick256256/java-filmorate pull request #1
Opened 2022-12-25 12:01 UTC by Danchick256256

2022-12-26 11:31 UTC, krylov-sergey-sergeevich requested changes
Привет, давай доработаем этот pr и будет зачет

2022-12-26 11:31 UTC, krylov-sergey-sergeevich commented on .mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
В гитигнор

2022-12-26 11:31 UTC, krylov-sergey-sergeevich commented on mvnw
> +#!/bin/sh
В гитигнор

2022-12-26 11:31 UTC, krylov-sergey-sergeevich commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
В гитигнор

2022-12-26 11:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!film.getReleaseDate().isAfter(LocalDate.parse("1895-12-28", DateTimeFormatter.ofPattern("yyyy-MM-dd")))) {
DateTimeFormatter.ofPattern("yyyy-MM-dd") - давай вынесем в класс констант

2022-12-26 11:31 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmsTest.java
> +    void createFilm() {
Проверил что Valid срабатывает?

2022-12-26 12:01 UTC, Danchick256256 commented on src/test/java/ru/yandex/practicum/filmorate/FilmsTest.java
> +    void createFilm() {
@Valid не работает на Unit тестах я сделал доп. валидацию

2022-12-27 05:22 UTC, krylov-sergey-sergeevich approved these changes
Привет, ну мы добили работу до состояния в котором она достойна зачета - поздравляю =)

p.s была судя по всему самая тяжелая дз среди всех у нас с тобой

2023-01-06 21:55 UTC, closed without merging