first review
Danchick256256/java-filmorate pull request #1
Opened 2022-12-21 14:18 UTC by Danchick256256

2022-12-21 14:21 UTC, Danchick256256 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +package ru.yandex.practicum.filmorate.controller;
Те тесты почему-то не проходят, а наставник не ответил по ним. Но вроде код можно проверить тут и тесты в постмане проходят

2022-12-21 14:24 UTC, Danchick256256 commented on .gitignore
> -*.class
Те тесты почему-то не проходят, а наставник не ответил по ним. Но вроде код можно проверить тут и тесты в постмане проходят

2022-12-22 16:34 UTC, krylov-sergey-sergeevich requested changes
Привет, не все вроде как из ТЗ учтено:

0) то что в коде отметил
1) дата релиза — не раньше 28 декабря 1895 года;
2) Добавьте тесты для валидации. Убедитесь, что она работает на граничных условиях.

+ надо сделать так чтобы обязательно сборка собиралась и проверка проходила и была зеленая в PR

Буду ждать с правками =)

2022-12-22 16:34 UTC, krylov-sergey-sergeevich commented on .gitignore
> -*.class
Я проверю работу, но пока тут тесты не пройдут я не могу принять работу

2022-12-22 16:34 UTC, krylov-sergey-sergeevich commented on mvnw
> +#!/bin/sh
Этот файл надо в gitignore добавить

2022-12-22 16:34 UTC, krylov-sergey-sergeevich commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
Этот файл надо в gitignore добавить

2022-12-22 16:34 UTC, krylov-sergey-sergeevich commented on .mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
Этот и файл рядом в папке обычно в github не добавляют, но не критично

2022-12-22 16:34 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>1.18.24</version>
Версию можно вынести в блок properties в pom, можно почитать об этом если будет желание

2022-12-22 16:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
Почему этот логгер а не ломбока?

2022-12-22 16:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    HashMap<Integer, Film> films = new HashMap<>();
Модификатор доступа

2022-12-22 16:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
Логгер заменить на аннотацию логгера от ломбока

2022-12-24 08:42 UTC, closed without merging